##
# Recreate ADT Instance
#
# @file
# @version 1.0
makeFileDir := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

init:
	pip install -r requirements.txt
clean:
	rm -r $(makeFileDir)__pycache__
# end
